# This is a basic workflow to help you get started with Actions 

name: notify CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch 
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: 'Install node'
        uses: actions/setup-node@v1
      - name: 'Install NPM dependencies'
        run: npm install  
      - name: 'install node mailer'
        run: npm install nodemailer
      - name: 'Install node telegram bot'
        run: npm install --save node-telegram-bot-api
      - name: 'install dotenv'
        run: npm install dotenv
      - name: 'install node fetch'
        run: npm install node-fetch      
  
        
      # Runs code
      - name: 'Run messaging code'
        run: node messagingapp.js
        env:
          GMAILUSER: ${{ secrets.GMAILUSER }}
          GMAILPASS: ${{ secrets.GMAILPASSWORD }}
          TELEGRAMCHATID: ${{secrets.TELEGRAM_CHAT_ID}}
          TELEGRAMTOKEN: ${{secrets.TELEGRAM_TOKEN}}
          WEATHERTOKEN: ${{secrets.WEATHER_API_TOKEN}}
          


    
